# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../notebooks/06_Export.ipynb.

# %% ../../../notebooks/06_Export.ipynb #a8cf3654
from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd

from .import_data import PROJECT_ROOT

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

logger = logging.getLogger("myproj.io")

# %% auto #0
__all__ = ['PROCESSED_DIR', 'logger', 'save_processed_data']

# %% ../../../notebooks/06_Export.ipynb #352e2cfa
def save_processed_data(df: pd.DataFrame, filename: str) -> Path:
    """Speichert einen DataFrame als Parquet in data/processed/."""
    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    path = PROCESSED_DIR / filename
    df.to_parquet(path, index=False)
    logger.info(
        "save_processed_data | file: %s | rows: %d | cols: %d",
        filename, len(df), len(df.columns),
    )
    return path
