# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../notebooks/01_Import.ipynb.

# %% ../../../notebooks/01_Import.ipynb #e10673ba
from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd
import xarray as xr

logger = logging.getLogger("myproj.io")

# %% auto #0
__all__ = [
    "logger",
    "PROJECT_ROOT",
    "DATA_RAW",
    "find_project_root",
    "get_raw_file_path",
    "load_raw_data",
]


# %% ../../../notebooks/01_Import.ipynb #8f889341
def find_project_root() -> Path:
    """
    Findet den Projektroot, indem vom aktuellen Arbeitsverzeichnis
    nach oben gesucht wird, bis eine pyproject.toml gefunden wird.
    """
    current = Path.cwd().resolve()
    logger.debug("Suche Projektroot ab: %s", current)

    for path in [current, *current.parents]:
        if (path / "pyproject.toml").exists():
            logger.debug("Projektroot gefunden: %s", path)
            return path

    logger.error("Projektroot nicht gefunden ab: %s", current)
    raise FileNotFoundError(
        "Projektroot nicht gefunden. Stelle sicher, dass du im Projekt "
        "oder in einem Unterordner des Projekts arbeitest."
    )


PROJECT_ROOT = find_project_root()
DATA_RAW = PROJECT_ROOT / "data" / "raw"


# %% ../../../notebooks/01_Import.ipynb #d9e00604
def get_raw_file_path(filename: str) -> Path:
    """
    Gibt den vollständigen Pfad zu einer Datei im data/raw-Ordner zurück.
    """
    file_path = DATA_RAW / filename

    if not file_path.exists():
        logger.error("Rohdatei nicht gefunden: %s", file_path)
        raise FileNotFoundError(f"Datei nicht gefunden: {file_path}")

    logger.debug("Rohdatei gefunden: %s", file_path)
    return file_path


# %% ../../../notebooks/01_Import.ipynb #bd3b4471
def load_raw_data(filename: str):
    """
    Lädt eine Datei aus data/raw abhängig von ihrer Dateiendung.

    Unterstützte Formate:
    - .xlsx, .xls -> pandas DataFrame
    - .nc -> xarray Dataset
    """
    file_path = get_raw_file_path(filename)
    suffix = file_path.suffix.lower()
    logger.info("Lade Rohdatei: %s", file_path.name)

    if suffix in {".xlsx", ".xls"}:
        df = pd.read_excel(file_path)
        logger.info(
            "load_raw_data | file: %s | rows: %d | cols: %d",
            filename,
            len(df),
            len(df.columns),
        )
        return df

    if suffix == ".nc":
        ds = xr.open_dataset(file_path, engine="h5netcdf")
        logger.info(
            "load_raw_data | file: %s | variables: %d | dimensions: %s",
            filename,
            len(ds.data_vars),
            dict(ds.sizes),
        )
        return ds

    raise ValueError(
        f"Nicht unterstütztes Dateiformat: {suffix}. Unterstützt werden .xlsx, .xls, .nc"
    )
