# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../notebooks/02_Filter.ipynb.

# %% ../../../notebooks/02_Filter.ipynb #32429a6e
from __future__ import annotations

import logging

import pandas as pd

logger = logging.getLogger("myproj.transform")

# %% auto #0
__all__ = ['logger', 'MED_ISO', 'select_columns', 'filter_to_sea_level_coverage', 'filter_to_floods', 'filter_to_mediterranean']

# %% ../../../notebooks/02_Filter.ipynb #c18045af
def select_columns(df: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    """Nur angegebene Spalten behalten. Raises ValueError bei fehlenden Spalten."""
    missing = [c for c in columns if c not in df.columns]
    if missing:
        logger.error("Spaltenauswahl fehlgeschlagen; fehlende Spalten: %s", missing)
        raise ValueError(f"Spalten nicht vorhanden im DataFrame: {missing}")
    result = df[columns].copy()
    logger.info(
        "select_columns | cols: %d → %d",
        len(df.columns),
        len(columns),
    )
    return result

# %% ../../../notebooks/02_Filter.ipynb #e90d11e3
def filter_to_sea_level_coverage(
    df: pd.DataFrame,
    sea_level: pd.DataFrame,
    time_col: str = "time",
    year_col: str = "Start Year",
    month_col: str = "Start Month",
    day_col: str = "Start Day",
) -> pd.DataFrame:
    """
    Behält nur EMDAT-Einträge innerhalb der Sea-Level-Abdeckung.
    Einträge mit fehlenden Datumswerten werden verworfen, da sie nicht
    eindeutig der Abdeckungsperiode zugeordnet werden können.
    """
    s = pd.to_datetime(sea_level[time_col].min())
    e = pd.to_datetime(sea_level[time_col].max())

    date_lower = pd.to_datetime(pd.DataFrame({
        "year": df[year_col], "month": df[month_col].fillna(1), "day": df[day_col].fillna(1),
    }), errors="coerce")
    date_upper = pd.to_datetime(pd.DataFrame({
        "year": df[year_col], "month": df[month_col].fillna(12), "day": df[day_col].fillna(28),
    }), errors="coerce")

    mask = (date_lower >= s) & (date_upper <= e)
    result = df[mask].copy()
    logger.info(
        "filter_to_sea_level_coverage | rows: %d → %d | removed before: %d | removed after: %d | coverage: %s – %s",
        len(df), len(result),
        int((date_lower < s).sum()),
        int((date_upper > e).sum()),
        s.date(), e.date(),
    )
    return result

# %% ../../../notebooks/02_Filter.ipynb #e95c017e
def filter_to_floods(df: pd.DataFrame) -> pd.DataFrame:
    """Behält nur Zeilen, bei denen Disaster Type oder Disaster Subtype 'flood' enthält."""
    mask = (
        df["Disaster Type"].str.contains("flood", case=False, na=False)
        | df["Disaster Subtype"].str.contains("flood", case=False, na=False)
    )
    result = df[mask].copy()
    logger.info(
        "filter_to_floods | rows: %d → %d | removed: %d",
        len(df), len(result), len(df) - len(result),
    )
    return result

# %% ../../../notebooks/02_Filter.ipynb #3fe5207d
MED_ISO = [
    "ALB", "DZA", "BIH", "HRV", "CYP", "EGY", "FRA", "GRC", "ISR", "ITA",
    "LBN", "LBY", "MLT", "MNE", "MAR", "PSE", "SVN", "ESP", "SYR", "TUN", "TUR",
]

# %% ../../../notebooks/02_Filter.ipynb #ef105138
def filter_to_mediterranean(
    df: pd.DataFrame, iso_codes: list[str] = MED_ISO
) -> pd.DataFrame:
    """Behält nur Zeilen aus Mittelmeerländern gemäss ISO-Ländercodes."""
    result = df[df["ISO"].isin(iso_codes)].copy()
    logger.info(
        "filter_to_mediterranean | rows: %d → %d | removed: %d",
        len(df), len(result), len(df) - len(result),
    )
    return result
