# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../notebooks/02_Transform.ipynb.

# %% ../../../notebooks/02_Transform.ipynb #32429a6e
from __future__ import annotations

import logging

import pandas as pd

logger = logging.getLogger("myproj.transform")

# %% auto #0
__all__ = ["logger", "select_columns", "filter_to_sea_level_coverage"]


# %% ../../../notebooks/02_Transform.ipynb #c18045af
def select_columns(df: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    """Nur angegebene Spalten behalten. Raises ValueError bei fehlenden Spalten."""
    missing = [c for c in columns if c not in df.columns]
    if missing:
        logger.error("Spaltenauswahl fehlgeschlagen; fehlende Spalten: %s", missing)
        raise ValueError(f"Spalten nicht vorhanden im DataFrame: {missing}")
    result = df[columns].copy()
    logger.info(
        "select_columns | cols: %d → %d",
        len(df.columns),
        len(columns),
    )
    return result


# %% ../../../notebooks/02_Transform.ipynb #e90d11e3
def filter_to_sea_level_coverage(
    df: pd.DataFrame,
    sea_level: pd.DataFrame,
    time_col: str = "time",
    year_col: str = "Start Year",
    month_col: str = "Start Month",
    day_col: str = "Start Day",
) -> pd.DataFrame:
    """
    Behält nur EMDAT-Einträge innerhalb der Sea-Level-Abdeckung.
    Einträge mit fehlenden Datumswerten werden verworfen, da sie nicht
    eindeutig der Abdeckungsperiode zugeordnet werden können.
    """
    s = pd.to_datetime(sea_level[time_col].min())
    e = pd.to_datetime(sea_level[time_col].max())

    date_lower = pd.to_datetime(
        pd.DataFrame(
            {
                "year": df[year_col],
                "month": df[month_col].fillna(1),
                "day": df[day_col].fillna(1),
            }
        ),
        errors="coerce",
    )
    date_upper = pd.to_datetime(
        pd.DataFrame(
            {
                "year": df[year_col],
                "month": df[month_col].fillna(12),
                "day": df[day_col].fillna(28),
            }
        ),
        errors="coerce",
    )

    mask = (date_lower >= s) & (date_upper <= e)
    result = df[mask].copy()
    logger.info(
        "filter_to_sea_level_coverage | rows: %d → %d | removed before: %d | removed after: %d | coverage: %s – %s",
        len(df),
        len(result),
        int((date_lower < s).sum()),
        int((date_upper > e).sum()),
        s.date(),
        e.date(),
    )
    return result
