# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/",
        "doc_host": "",
        "git_url": "",
        "lib_path": "src/myproj",
    },
    "syms": {
        "myproj.cleaning.clean": {
            "myproj.cleaning.clean.drop_duplicates": (
                "cleaning.html#drop_duplicates",
                "myproj/cleaning/clean.py",
            ),
            "myproj.cleaning.clean.drop_impossible_dates": (
                "cleaning.html#drop_impossible_dates",
                "myproj/cleaning/clean.py",
            ),
            "myproj.cleaning.clean.drop_missing_start_year": (
                "cleaning.html#drop_missing_start_year",
                "myproj/cleaning/clean.py",
            ),
            "myproj.cleaning.clean.impute_missing_measurements": (
                "cleaning.html#impute_missing_measurements",
                "myproj/cleaning/clean.py",
            ),
        },
        "myproj.io.export_data": {
            "myproj.io.export_data.save_processed_data": (
                "export.html#save_processed_data",
                "myproj/io/export_data.py",
            )
        },
        "myproj.io.import_data": {
            "myproj.io.import_data.find_project_root": (
                "import.html#find_project_root",
                "myproj/io/import_data.py",
            ),
            "myproj.io.import_data.get_raw_file_path": (
                "import.html#get_raw_file_path",
                "myproj/io/import_data.py",
            ),
            "myproj.io.import_data.load_raw_data": (
                "import.html#load_raw_data",
                "myproj/io/import_data.py",
            ),
        },
        "myproj.link.join": {
            "myproj.link.join._mean_sea_level": (
                "join.html#_mean_sea_level",
                "myproj/link/join.py",
            ),
            "myproj.link.join.drop_join_redundant_cols": (
                "join.html#drop_join_redundant_cols",
                "myproj/link/join.py",
            ),
            "myproj.link.join.join_sea_level": ("join.html#join_sea_level", "myproj/link/join.py"),
            "myproj.link.join.prepare_sea_level_ts": (
                "join.html#prepare_sea_level_ts",
                "myproj/link/join.py",
            ),
        },
        "myproj.pipeline": {},
        "myproj.transform.filter": {
            "myproj.transform.filter.filter_to_floods": (
                "filter.html#filter_to_floods",
                "myproj/transform/filter.py",
            ),
            "myproj.transform.filter.filter_to_mediterranean": (
                "filter.html#filter_to_mediterranean",
                "myproj/transform/filter.py",
            ),
            "myproj.transform.filter.filter_to_sea_level_coverage": (
                "filter.html#filter_to_sea_level_coverage",
                "myproj/transform/filter.py",
            ),
            "myproj.transform.filter.select_columns": (
                "filter.html#select_columns",
                "myproj/transform/filter.py",
            ),
        },
        "myproj.transform.transform": {
            "myproj.transform.transform._date_quality": (
                "transform.html#_date_quality",
                "myproj/transform/transform.py",
            ),
            "myproj.transform.transform._make_event_date": (
                "transform.html#_make_event_date",
                "myproj/transform/transform.py",
            ),
            "myproj.transform.transform._season_from_month": (
                "transform.html#_season_from_month",
                "myproj/transform/transform.py",
            ),
            "myproj.transform.transform.add_derived_columns": (
                "transform.html#add_derived_columns",
                "myproj/transform/transform.py",
            ),
            "myproj.transform.transform.add_event_dates": (
                "transform.html#add_event_dates",
                "myproj/transform/transform.py",
            ),
            "myproj.transform.transform.add_sea_level_lags": (
                "transform.html#add_sea_level_lags",
                "myproj/transform/transform.py",
            ),
            "myproj.transform.transform.add_sea_level_z_scores": (
                "transform.html#add_sea_level_z_scores",
                "myproj/transform/transform.py",
            ),
        },
    },
}
