# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "main",
        "doc_baseurl": "/",
        "doc_host": "",
        "git_url": "",
        "lib_path": "src/myproj",
    },
    "syms": {
        "myproj.cleaning.clean": {
            "myproj.cleaning.clean.drop_duplicates": (
                "cleaning.html#drop_duplicates",
                "myproj/cleaning/clean.py",
            ),
            "myproj.cleaning.clean.drop_impossible_dates": (
                "cleaning.html#drop_impossible_dates",
                "myproj/cleaning/clean.py",
            ),
            "myproj.cleaning.clean.drop_missing_start_year": (
                "cleaning.html#drop_missing_start_year",
                "myproj/cleaning/clean.py",
            ),
            "myproj.cleaning.clean.impute_missing_measurements": (
                "cleaning.html#impute_missing_measurements",
                "myproj/cleaning/clean.py",
            ),
        },
        "myproj.io.import_data": {
            "myproj.io.import_data.find_project_root": (
                "import.html#find_project_root",
                "myproj/io/import_data.py",
            ),
            "myproj.io.import_data.get_raw_file_path": (
                "import.html#get_raw_file_path",
                "myproj/io/import_data.py",
            ),
            "myproj.io.import_data.load_raw_data": (
                "import.html#load_raw_data",
                "myproj/io/import_data.py",
            ),
        },
        "myproj.pipeline": {},
        "myproj.transform.trim_data": {
            "myproj.transform.trim_data.filter_to_sea_level_coverage": (
                "transform.html#filter_to_sea_level_coverage",
                "myproj/transform/trim_data.py",
            ),
            "myproj.transform.trim_data.select_columns": (
                "transform.html#select_columns",
                "myproj/transform/trim_data.py",
            ),
        },
    },
}
