# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../notebooks/03_Cleaning.ipynb.

# %% ../../../notebooks/03_Cleaning.ipynb #62c0db2d
from __future__ import annotations

import logging

import pandas as pd

from .._utils import fmt_ids

logger = logging.getLogger("myproj.cleaning")

# %% auto #0
__all__ = ['logger', 'drop_duplicates', 'drop_impossible_dates', 'drop_missing_start_year', 'impute_missing_measurements']

# %% ../../../notebooks/03_Cleaning.ipynb #fca5a5a1
def drop_duplicates(df: pd.DataFrame, id_col: str) -> pd.DataFrame:
    """Entfernt Zeilen mit doppeltem id_col (keep='first') und loggt die entfernten IDs."""
    dup_mask = df.duplicated(subset=[id_col], keep="first")
    n = int(dup_mask.sum())
    ids = df.loc[dup_mask, id_col].astype(str).tolist()
    logger.info("drop_duplicates | id_col: %s | removed: %d | %s", id_col, n, fmt_ids(ids))
    return df[~dup_mask].copy()

# %% ../../../notebooks/03_Cleaning.ipynb #a18e6b41
def drop_impossible_dates(
    df: pd.DataFrame,
    start_col: str = "Start Year",
    end_col: str = "End Year",
    id_col: str = "DisNo.",
) -> pd.DataFrame:
    """Entfernt Zeilen, bei denen End Year < Start Year (logisch unmöglich)."""
    mask = df[end_col].notna() & df[start_col].notna() & (df[end_col] < df[start_col])
    n = int(mask.sum())
    ids = df.loc[mask, id_col].astype(str).tolist()
    logger.info("drop_impossible_dates | removed: %d | %s", n, fmt_ids(ids))
    return df[~mask].copy()

# %% ../../../notebooks/03_Cleaning.ipynb #f1a881a4
def drop_missing_start_year(
    df: pd.DataFrame,
    year_col: str = "Start Year",
    id_col: str = "DisNo.",
) -> pd.DataFrame:
    """Entfernt Zeilen ohne Start Year (zeitlich nicht einordenbar)."""
    mask = df[year_col].isna()
    n = int(mask.sum())
    ids = df.loc[mask, id_col].astype(str).tolist()
    logger.info("drop_missing_start_year | removed: %d | %s", n, fmt_ids(ids))
    return df[~mask].copy()

# %% ../../../notebooks/03_Cleaning.ipynb #92a36ee0
def impute_missing_measurements(
    df: pd.DataFrame,
    time_col: str = "time",
    cols: list[str] | None = None,
) -> pd.DataFrame:
    """Imputiert fehlende Messwerte per linearer Interpolation.

    Randwerte werden durch ffill/bfill aufgefüllt, da lineare Interpolation
    dort keinen zweiten Ankerpunkt hat.
    """
    if cols is None:
        cols = [
            "MSL_filtered_GIA_corrected_adjusted",
            "trend_MSL_filtered_GIA_corrected_adjusted",
        ]
    df = df.copy()
    for col in cols:
        mask = df[col].isna()
        n = int(mask.sum())
        timestamps = df.loc[mask, time_col].dt.strftime("%Y-%m-%d").tolist()
        df[col] = df[col].interpolate(method="linear").ffill().bfill()
        logger.info("impute_missing_measurements | col: %s | imputed: %d | %s", col, n, fmt_ids(timestamps))
    return df
